name: Auto Release

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v3

      - name: Obtener versión desde archivo VERSION
        id: version
        run: |
          VERSION=$(cat VERSION)
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      - name: Crear Tag
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git tag $VERSION
          git push origin $VERSION

      - name: Crear Release en GitHub
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ env.VERSION }}
