name: Auto Release

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v3

      - name: Generar versión automática
        run: echo "VERSION=v1.0.${{ github.run_number }}" >> $GITHUB_ENV

      - name: Crear Tag
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git tag $VERSION
          git push origin $VERSION

      - name: Crear Release en GitHub
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ env.VERSION }}
